<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2c71702847e101ff39bf20e94e594120
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Container\\' => 14,
        ),
        'L' =>
        array (
            'Loq\\Lab5Mvc\\' => 12,
        ),
        'F' =>
        array (
            'Faker\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Container\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Loq\\Lab5Mvc\\' =>
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
        'Faker\\' =>
        array (
            0 => __DIR__ . '/..' . '/fakerphp/faker/src/Faker',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2c71702847e101ff39bf20e94e594120::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2c71702847e101ff39bf20e94e594120::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2c71702847e101ff39bf20e94e594120::$classMap;

        }, null, ClassLoader::class);
    }
}
